name: 'Publish OpenAPI from TypeScript'
description: 'Extrait le contrat d un BFF TS, compile et publie les types'

inputs:
  version:
    required: true
    description: 'Version du package à publier'
  package_name:
    required: true
    description: 'Nom du package à publier'
  dist_tag:
    required: false
    description: "npm dist-tag à utiliser (ex: dev, staging, ou vide pour latest)"
    default: "latest"
  token:
    required: true
    description: 'Token d authentification GitHub'

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        # [CHANGEMENT] Ajout de 'set -e' pour stopper net le script en cas d'erreur
        # et éviter des échecs silencieux lors de la préparation du package.
        set -e

        ORG=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        SAFE_NAME=$(echo "${{ inputs.package_name }}" | tr '[:upper:]' '[:lower:]')

        rm -rf ./dist_pkg
        mkdir -p ./dist_pkg

        echo "Dossier de staging initialisé pour : @${ORG}/${SAFE_NAME}-openapi"
