name: "Semantic Tag & Release"
description: "Calcule la version, crée le tag et la release GitHub via Semantic Release"

outputs:
  new_release_published:
    description: "true si une nouvelle version est publiée"
    value: ${{ steps.semantic.outputs.new_release_published }}
  new_release_version:
    description: "La version calculée (ex: 1.2.0)"
    value: ${{ steps.semantic.outputs.new_release_version }}

runs:
  using: "composite"
  steps:
    - name: Install semantic-release-cargo
      shell: bash
      run: npm install -g semantic-release-cargo

    - name: Semantic Release
      id: semantic
      uses: cycjimmy/semantic-release-action@v6.0.0
      with:
        config_file: release.config.js # Pointe vers notre config Rust
      env:
        GITHUB_TOKEN: ${{ github.token }}