name: Docker Build Temporary Manual

on:
  workflow_call:
    inputs:
      package_name:
        description: 'Name of the package group'
        required: true
        type: string

permissions:
  contents: read
  packages: write

run:
  using: "composite"
  steps:
    - name: Check branch
      if: github.ref == 'refs/heads/main'
      run: |
        echo "This workflow cannot be run on the main branch."
        exit 1

    - name: Checkout repository
      uses: actions/checkout@v4.2.2

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/${{ inputs.package_name }}:${{ github.ref_name }}-${{ github.sha }} .

    - name: Push Docker image
      run: docker push ghcr.io/${{ github.repository_owner }}/${{ inputs.package_name }}:${{ github.ref_name }}-${{ github.sha }}
