#!/usr/bin/env bash
# Génère le paquet TypeScript @<org>/<nom>-openapi depuis un contrat OpenAPI (JSON).
# Partagé par publish-openapi-rust et publish-openapi-typescript : même contenu pour les APIs et les BFFs.
#
# Le paquet ne contient que du TypeScript, tout dérivé du même contrat :
#   endpoints/*.ts, model/*.ts  client axios orval (chemins inchangés pour les consommateurs existants)
#   zod/index.ts                schémas zod orval : formats, bornes, valeurs par défaut (réponses de succès)
#   openapi.ts                  types openapi-typescript : paths/components/operations, tous statuts et en-têtes
#   contract.ts                 le contrat complet en valeur (`as const`), pour les proxys et mocks
#   index.ts                    ré-exports
#
# Usage : generate.sh <contrat.json> <dossier de sortie> <nom du paquet npm> <version>
set -euo pipefail

SPEC_FILE=${1:?contrat OpenAPI requis}
OUT_DIR=${2:?dossier de sortie requis}
NPM_NAME=${3:?nom du paquet requis}
VERSION=${4:?version requise}

# Versions épinglées : la sortie du paquet ne doit changer qu'avec le contrat.
ORVAL_VERSION=8.33.0
OPENAPI_TYPESCRIPT_VERSION=7.10.1

if [ ! -s "$SPEC_FILE" ]; then
  echo "::error::Contrat OpenAPI introuvable ou vide : '$SPEC_FILE'"
  exit 1
fi
SPEC_PATH=$(realpath "$SPEC_FILE")
rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR"
OUT_DIR=$(realpath "$OUT_DIR")
WORK_DIR=$(mktemp -d)
trap 'rm -rf "$WORK_DIR"' EXIT

# 1. Clients orval (hors du repo appelant pour ignorer toute config orval locale).
cat > "$WORK_DIR/orval.config.cjs" <<EOF
module.exports = {
  axios: {
    input: "${SPEC_PATH}",
    output: {
      mode: "split",
      target: "${OUT_DIR}/endpoints",
      schemas: "${OUT_DIR}/model",
      client: "axios",
      mock: false,
    },
  },
  zod: {
    input: "${SPEC_PATH}",
    output: {
      mode: "single",
      target: "${OUT_DIR}/zod/index.ts",
      client: "zod",
      mock: false,
    },
  },
};
EOF
(cd "$WORK_DIR" && npx -y "orval@${ORVAL_VERSION}" --config "$WORK_DIR/orval.config.cjs")

# 2. Types de toutes les réponses (erreurs et en-têtes compris).
npx -y "openapi-typescript@${OPENAPI_TYPESCRIPT_VERSION}" "$SPEC_PATH" --output "$OUT_DIR/openapi.ts"

# 3. Contrat en valeur, index et package.json.
node - "$SPEC_PATH" "$OUT_DIR" "$NPM_NAME" "$VERSION" <<'NODE'
const fs = require('node:fs');
const path = require('node:path');
const [specPath, outDir, npmName, version] = process.argv.slice(2);
const spec = JSON.parse(fs.readFileSync(specPath, 'utf8'));
const header = `/**\n * Generated by mairie360/CICD actions/openapi-package from the OpenAPI contract of ${npmName}@${version}.\n * Do not edit manually.\n */\n`;

fs.writeFileSync(path.join(outDir, 'contract.ts'),
  `${header}\n/** Contrat OpenAPI complet (chemins, statuts d'erreur, formats, en-têtes, exemples). */\nexport const contract = ${JSON.stringify(spec, null, 2)} as const;\n\nexport type Contract = typeof contract;\n`);

const endpoints = fs.readdirSync(path.join(outDir, 'endpoints')).filter((file) => file.endsWith('.ts')).sort();
fs.writeFileSync(path.join(outDir, 'index.ts'), `${header}\n${[
  ...endpoints.map((file) => `export * from './endpoints/${path.basename(file, '.ts')}';`),
  "export * from './model';",
  "export * as schemas from './zod';",
  "export type * as OpenApi from './openapi';",
  "export { contract } from './contract';",
  "export type { Contract } from './contract';",
].join('\n')}\n`);

fs.writeFileSync(path.join(outDir, 'package.json'), `${JSON.stringify({
  name: npmName,
  version,
  main: './index.ts',
  types: './index.ts',
  dependencies: { axios: '^1.0.0', zod: '^4.0.0' },
  publishConfig: { registry: 'https://npm.pkg.github.com' },
}, null, 2)}\n`);
NODE

# 4. Garde-fou : uniquement du TypeScript (plus package.json).
unexpected=$(cd "$OUT_DIR" && find . -type f ! -name '*.ts' ! -path './package.json')
if [ -n "$unexpected" ]; then
  echo "::error::Fichiers non TypeScript dans le paquet : $unexpected"
  exit 1
fi
