name: Docker Publish
description: Push Docker images to GHCR

inputs:
  package_name:
    description: 'Name of the package'
    required: true
  environment:
    description: 'Deployment environment'
    required: true
  version:
    description: 'Version tag (optional)'
    required: false

runs:
  using: "composite"
  steps:
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

    - name: Push Docker image (sha or version)
      run: |
        TAG=${{ inputs.version || github.sha }}
        docker push ghcr.io/${{ github.repository_owner }}/${{ inputs.package_name }}:${{ inputs.environment }}-$TAG

    - name: Push Docker image (latest tag for environment)
      run: docker push ghcr.io/${{ github.repository_owner }}/${{ inputs.package_name }}:${{ inputs.environment }}-latest
