name: Docker Publish
description: Push Docker images to GHCR

inputs:
  package_name:
    description: 'Name of the package'
    required: true
  environment:
    description: 'Deployment environment'
    required: true
  version:
    description: 'Version tag (optional)'
    required: false
  github_token:
    description: 'GitHub token for authentication'
    required: true

runs:
  using: "composite"
  steps:
    - name: Log in to GitHub Container Registry
      run: echo "${{ inputs.github_token }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      shell: bash

    - name: Push Docker image (sha or version)
      run: |
        TAG=${{ inputs.version }}
        if [ -z "$TAG" ]; then
          TAG=${GITHUB_SHA}
        fi
        docker push ghcr.io/${GITHUB_REPOSITORY_OWNER}/${{ inputs.package_name }}:${{ inputs.environment }}-$TAG
      shell: bash

    - name: Push Docker image (latest tag for environment)
      run: docker push ghcr.io/${GITHUB_REPOSITORY_OWNER}/${{ inputs.package_name }}:${{ inputs.environment }}-latest
      shell: bash
