name: Database Prod Release Action
description: 'Action to release database package in prod environment'

inputs:
  package_name:
    description: 'Name of the package'
    required: true
  version:
    description: 'Version of the package'
    required: true

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/docker/build
      with:
        package_name: ${{ inputs.package_name }}
        environment: prod
        version: ${{ inputs.version }}
    - uses: ./.github/actions/docker/publish
      with:
        package_name: ${{ inputs.package_name }}
        environment: prod
        version: ${{ inputs.version }}
