# .github/actions/publish-openapi/action.yml
name: 'Publish OpenAPI Contract'
inputs:
  version:
    required: true
  package_name:
    required: true
  token:
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        ORG=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        SAFE_NAME=$(echo "${{ inputs.package_name }}" | tr '[:upper:]' '[:lower:]')
        
        # 1. Génération des fichiers
        cargo run --example generate_openapi --quiet > openapi.yaml
        npx openapi-typescript openapi.yaml -o index.d.ts
        
        # 2. Création d'un dossier propre pour la publication (staging)
        mkdir -p dist_package
        
        # 3. Création du package.json directement dans le dossier dist
        cat <<EOF > dist_package/package.json
        {
          "name": "@${ORG}/${SAFE_NAME}-openapi",
          "version": "${{ inputs.version }}",
          "main": "index.d.ts",
          "types": "index.d.ts",
          "publishConfig": { "registry": "https://npm.pkg.github.com" }
        }
        EOF
        
        # 4. Déplacement des types et config dans le dossier dist
        mv index.d.ts dist_package/
        echo "@${ORG}:registry=https://npm.pkg.github.com" > dist_package/.npmrc
        echo "//npm.pkg.github.com/:_authToken=${{ inputs.token }}" >> dist_package/.npmrc
        
        # 5. Publication DEPUIS le dossier dist
        cd dist_package
        npm publish