name: 'Publish OpenAPI Contract'
description: 'Génère et publie le contrat OpenAPI'

inputs:
  version:
    required: true
  package_name:
    required: true
  token:
    required: true
  language:
    required: true
    description: "Le langage du projet source : 'rust' ou 'typescript'"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        ORG=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        SAFE_NAME=$(echo "${{ inputs.package_name }}" | tr '[:upper:]' '[:lower:]')
        
        # [IMPORTANT] Configurer l'auth npm globalement pour cette exécution
        # Cela permet au 'npm install' de fonctionner pour les dépendances privées
        echo "@${ORG}:registry=https://npm.pkg.github.com" > ~/.npmrc
        echo "//npm.pkg.github.com/:_authToken=${{ inputs.token }}" >> ~/.npmrc

        # --- LOGIQUE POUR LES PROJETS RUST ---
        if [ "${{ inputs.language }}" = "rust" ]; then
          echo "🦀 Source détectée : Rust"
          cargo run --example generate_openapi --quiet > openapi.json
          
          npx openapi-typescript openapi.json -o index.d.ts
          
          mkdir -p dist_pkg
          cat <<EOF > dist_pkg/package.json
          {
            "name": "@${ORG}/${SAFE_NAME}-openapi",
            "version": "${{ inputs.version }}",
            "main": "index.d.ts",
            "types": "index.d.ts",
            "publishConfig": { "registry": "https://npm.pkg.github.com" }
          }
        EOF
          mv index.d.ts dist_pkg/
          cp ~/.npmrc dist_pkg/.npmrc # On réutilise le config créé au début
          
          cd dist_pkg && npm publish

        # --- LOGIQUE POUR LES PROJETS TYPESCRIPT (BFF) ---
        elif [ "${{ inputs.language }}" = "typescript" ]; then
          echo "📦 Source détectée : TypeScript"
          
          # Maintenant npm install fonctionnera car ~/.npmrc existe
          npm install --legacy-peer-deps
          npm run openapi:extract 
          
          npx openapi-typescript openapi.json -o index.d.ts
          
          mkdir -p dist_pkg
          cat <<EOF > dist_pkg/package.json
          {
            "name": "@${ORG}/${SAFE_NAME}-openapi",
            "version": "${{ inputs.version }}",
            "main": "index.d.ts",
            "types": "index.d.ts",
            "publishConfig": { "registry": "https://npm.pkg.github.com" }
          }
        EOF
          mv index.d.ts dist_pkg/
          cp ~/.npmrc dist_pkg/.npmrc
          
          cd dist_pkg && npm publish
        fi