name: Back CD Workflow

on:
  workflow_call:
    inputs:
      job:
        required: true
        type: string
      environment:
        required: true
        type: string
      version:
        required: false
        type: string

jobs:
  run:
    strategy:
      matrix:
        include:
          - job: release
            environment: dev
            uses_docker_build: true

          - job: deploy
            environment: dev

          - job: release
            environment: staging
            uses_docker_build: true

          - job: deploy
            environment: staging

          - job: release
            environment: prod
            require_version: true

          - job: deploy
            environment: prod
            require_version: true

    if: |
      matrix.job == inputs.job &&
      matrix.environment == inputs.environment &&
      ( !matrix.require_version || inputs.version != '' )

    runs-on: ubuntu-latest

    steps:
      - name: Debug info
        run: echo "Running ${{ matrix.job }} for ${{ matrix.environment }} (version=${{ inputs.version }})"

      # === Release steps ===
      - name: Run docker build
        if: ${{ matrix.uses_docker_build }}
        uses: ./.github/workflows/docker_build.yml
        with:
          package_name: "database"
          environment: ${{ matrix.environment }}

      # === Deploy steps ===
      - name: Run deployment
        if: ${{ matrix.job == 'deploy' }}
        run: echo "Running back CD for ${{ matrix.environment }}"
