name: Database CI/CD

on:
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
      cicd_version:
        required: true
        type: string
    secrets:
      GH_PAT:
        required: true

jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      
      - name: Run tests
        run: ./test.sh
    
  
  release-dev:
    needs: tests
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: Dev
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build & Push Images (Dev)
        run: |
          SHA_TAG=${GITHUB_SHA::7}
          REPO="ghcr.io/${GITHUB_REPOSITORY_OWNER,,}"

          docker build \
            -t $REPO/${{ inputs.package_name }}:dev-$SHA_TAG \
            -t $REPO/${{ inputs.package_name }}:dev-latest .

          # 2. Build de l'image Liquibase
          docker build \
            -f liquibase/Dockerfile \
            -t $REPO/liquibase-migrations:dev-$SHA_TAG \
            -t $REPO/liquibase-migrations:dev-latest .

          # Push des images
          docker push $REPO/${{ inputs.package_name }} --all-tags
          docker push $REPO/liquibase-migrations --all-tags

  release-staging:
    needs: release-dev
    runs-on: ubuntu-latest
    environment: Staging
    permissions:
      contents: read
      packages: write
    steps:
      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Promote Images to Staging
        run: |
          SHA_TAG=${GITHUB_SHA::7}
          REPO="ghcr.io/${GITHUB_REPOSITORY_OWNER,,}"

          # Promotion de l'image DB
          docker pull $REPO/${{ inputs.package_name }}:dev-$SHA_TAG
          docker tag $REPO/${{ inputs.package_name }}:dev-$SHA_TAG $REPO/${{ inputs.package_name }}:staging-$SHA_TAG
          docker tag $REPO/${{ inputs.package_name }}:dev-$SHA_TAG $REPO/${{ inputs.package_name }}:staging-latest
          docker push $REPO/${{ inputs.package_name }} --all-tags

          # Promotion de l'image Liquibase
          docker pull $REPO/liquibase-migrations:dev-$SHA_TAG
          docker tag $REPO/liquibase-migrations:dev-$SHA_TAG $REPO/liquibase-migrations:staging-$SHA_TAG
          docker tag $REPO/liquibase-migrations:dev-$SHA_TAG $REPO/liquibase-migrations:staging-latest
          docker push $REPO/liquibase-migrations --all-tags

  release-prod:
    needs: release-staging
    runs-on: ubuntu-latest
    environment: Prod
    permissions:
      contents: write
      packages: write
    outputs:
      PUBLISHED: ${{ steps.set_tag.outputs.new_release_published }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          
      - name: Checkout CICD Tools
        uses: actions/checkout@v6
        with:
          repository: mairie360/CICD
          ref: ${{ inputs.cicd_version }}
          path: cicd-repo
      
      - name: Calculate & Create Tag
        id: set_tag
        uses: ./.github/actions/semantic-tag
        with:
          cicd_path: cicd-repo
  
      - name: Log in to GHCR
        if: steps.set_tag.outputs.new_release_published == 'true'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
  
      - name: Promote Images to Prod
        if: steps.set_tag.outputs.new_release_published == 'true'
        run: |
          SHA_TAG=${GITHUB_SHA::7}
          REPO="ghcr.io/${GITHUB_REPOSITORY_OWNER,,}"
          TAG=${{ steps.set_tag.outputs.new_release_version }}

          # Pull et Tag final pour la DB
          docker pull $REPO/${{ inputs.package_name }}:staging-$SHA_TAG
          docker tag $REPO/${{ inputs.package_name }}:staging-$SHA_TAG $REPO/${{ inputs.package_name }}:$TAG
          docker tag $REPO/${{ inputs.package_name }}:staging-$SHA_TAG $REPO/${{ inputs.package_name }}:latest
          docker push $REPO/${{ inputs.package_name }} --all-tags

          # Pull et Tag final pour Liquibase
          docker pull $REPO/liquibase-migrations:staging-$SHA_TAG
          docker tag $REPO/liquibase-migrations:staging-$SHA_TAG $REPO/liquibase-migrations:$TAG
          docker tag $REPO/liquibase-migrations:staging-$SHA_TAG $REPO/liquibase-migrations:latest
          docker push $REPO/liquibase-migrations --all-tags

  cleanup:
    name: Cleanup
    needs: release-prod
    if: needs.release-prod.outputs.PUBLISHED == 'true'
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Delete Old DB Images
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ inputs.package_name }}
          package-type: 'container'
          min-versions-to-keep: 3
          delete-only-pre-release-versions: 'true'

      - name: Delete Old Migration Images
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'liquibase-migrations'
          package-type: 'container'
          min-versions-to-keep: 3
          delete-only-pre-release-versions: 'true'